networks:
  stage-network:

services:
  stage-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STAGE: dev
    image: 'stage-server:latest'
    restart: always
    depends_on:
      - redis
      - mongo
    ports:
      - '3000:3000'
    networks:
      - stage-network

  redis:
    container_name: stage_redis
    image: redis
    restart: always
    volumes:
      - redis:/data
    expose:
      - 6379
    networks:
      - stage-network

  mongo:
    image: mongo:latest
    container_name: stage_mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - stage-network

volumes:
  redis:
    driver: local
